# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ProcessX
                                 A QGIS plugin
 This plugin provides diverse processing tools
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-06-05
        copyright            : (C) 2022 by Mario Koenigbauer
        email                : mkoenigb@gmx.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Mario Koenigbauer'
__date__ = '2022-06-05'
__copyright__ = '(C) 2022 by Mario Koenigbauer'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ProcessX class from file ProcessX.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .processx import ProcessXPlugin
    return ProcessXPlugin()
